export const revalidate = 3600;

import { JobList, type Job } from "./components/JobList";

const DATA_URL =
  "https://raw.githubusercontent.com/juancodez/job-search-bot/main/data/latest.json";

type Data = {
  generated_at: string;
  total: number;
  jobs: Job[];
};

async function getJobs(): Promise<Data | null> {
  try {
    const res = await fetch(DATA_URL, { next: { revalidate: 3600 } });
    if (!res.ok) return null;
    return res.json();
  } catch {
    return null;
  }
}

export default async function Page() {
  const data = await getJobs();

  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "48px 24px" }}>
      <div style={{ marginBottom: 40 }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, margin: 0 }}>
          Product Designer Jobs 🇪🇺
        </h1>
        <p style={{ color: "#666", marginTop: 8, fontSize: 14 }}>
          Updated weekly · DE · FR · NL · AT · CH
          {data && (
            <>
              {" "}· Last run:{" "}
              <span style={{ color: "#888" }}>
                {new Date(data.generated_at).toLocaleDateString("en-GB", {
                  weekday: "short",
                  day: "numeric",
                  month: "short",
                  year: "numeric",
                })}
              </span>
            </>
          )}
        </p>
      </div>

      {!data ? (
        <div style={{ color: "#555", textAlign: "center", padding: "60px 0" }}>
          No data yet — run the workflow first via GitHub Actions.
        </div>
      ) : (
        <JobList jobs={data.jobs} />
      )}

      <footer
        style={{
          marginTop: 64,
          borderTop: "1px solid #222",
          paddingTop: 24,
          color: "#444",
          fontSize: 12,
          textAlign: "center",
        }}
      >
        Auto-generated by{" "}
        <a
          href="https://github.com/juancodez/job-search-bot"
          style={{ color: "#555" }}
        >
          job-search-bot
        </a>
      </footer>
    </main>
  );
}
