"""
Weekly Product Designer job search across Europe.
Uses Adzuna API (free tier). Results posted as GitHub Issues.
"""

import os
import json
import requests
from datetime import datetime, timedelta

ADZUNA_APP_ID = os.environ["ADZUNA_APP_ID"]
ADZUNA_APP_KEY = os.environ["ADZUNA_APP_KEY"]
GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
GITHUB_REPO = os.environ["GITHUB_REPOSITORY"]

COUNTRIES = {
    "de": "Germany",
    "nl": "Netherlands",
    "fr": "France",
    "nl": "Netherlands",
    "at": "Austria",
    "ch": "Switzerland",
}

KEYWORDS = "product designer"
RESULTS_PER_COUNTRY = 10

JUNIOR_SIGNALS = ["junior", "entry", "graduate", "grad", "associate", "jr"]
SENIOR_SIGNALS = ["senior", "lead", "head", "principal", "director", "staff", "sr."]


def fetch_jobs(country_code: str, page: int = 1) -> list[dict]:
    url = f"https://api.adzuna.com/v1/api/jobs/{country_code}/search/{page}"
    params = {
        "app_id": ADZUNA_APP_ID,
        "app_key": ADZUNA_APP_KEY,
        "what": KEYWORDS,
        "results_per_page": RESULTS_PER_COUNTRY,
        "max_days_old": 7,
        "content-type": "application/json",
    }
    r = requests.get(url, params=params, timeout=15)
    r.raise_for_status()
    return r.json().get("results", [])


def score_job(job: dict) -> int:
    title = job.get("title", "").lower()
    desc = job.get("description", "").lower()

    score = 5

    # Title quality
    if "product designer" in title:
        score += 2
    elif "ux designer" in title or "ui/ux" in title:
        score += 1

    # Junior signals (good)
    if any(s in title for s in JUNIOR_SIGNALS):
        score += 2
    # Senior signals (bad — filter)
    if any(s in title for s in SENIOR_SIGNALS):
        score -= 4

    # Skills match
    for skill in ["figma", "prototyping", "user research", "design system", "wireframe"]:
        if skill in desc:
            score += 0.5

    # Remote/hybrid bonus
    if "remote" in desc or "hybrid" in desc:
        score += 0.5

    return round(min(max(score, 1), 10))


def format_salary(job: dict) -> str:
    sal = job.get("salary_min")
    if sal:
        return f"~€{int(sal):,}/yr"
    return "Not listed"


def build_issue_body(all_jobs: list[dict]) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    scored = sorted(all_jobs, key=lambda j: j["_score"], reverse=True)

    top = [j for j in scored if j["_score"] >= 8]
    good = [j for j in scored if 6 <= j["_score"] < 8]
    rest = [j for j in scored if j["_score"] < 6]

    lines = [
        f"# 🔍 Product Designer Jobs in Europe — {today}",
        f"\n**{len(all_jobs)} roles found** across {len(COUNTRIES)} countries · past 7 days\n",
    ]

    def render_section(title: str, jobs: list[dict]) -> list[str]:
        if not jobs:
            return []
        out = [f"\n## {title}\n"]
        for j in jobs:
            country = COUNTRIES.get(j["_country"], j["_country"].upper())
            out.append(f"### [{j['title']}]({j['redirect_url']}) — {j['company']['display_name']}")
            out.append(f"- **Location:** {j.get('location', {}).get('display_name', 'N/A')}, {country}")
            out.append(f"- **Salary:** {format_salary(j)}")
            out.append(f"- **Fit score:** {j['_score']}/10")
            out.append(f"- **Posted:** {j.get('created', 'N/A')[:10]}")
            out.append("")
        return out

    lines += render_section("🟢 Top Picks (8–10)", top)
    lines += render_section("🟡 Good Matches (6–7)", good)
    lines += render_section("⚪ Other Roles", rest[:5])

    lines += ["\n---", f"*Auto-generated by job-search-bot · {today}*"]
    return "\n".join(lines)


def post_github_issue(title: str, body: str) -> None:
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }
    payload = {"title": title, "body": body, "labels": ["job-search"]}
    r = requests.post(url, headers=headers, json=payload, timeout=15)
    r.raise_for_status()
    issue_url = r.json()["html_url"]
    print(f"Issue created: {issue_url}")


def main():
    all_jobs = []
    for code in COUNTRIES:
        print(f"Searching {COUNTRIES[code]}...")
        try:
            jobs = fetch_jobs(code)
            for j in jobs:
                j["_country"] = code
                j["_score"] = score_job(j)
            all_jobs.extend(jobs)
        except Exception as e:
            print(f"  Failed {code}: {e}")

    if not all_jobs:
        print("No jobs found.")
        return

    today = datetime.now().strftime("%Y-%m-%d")
    body = build_issue_body(all_jobs)
    post_github_issue(f"🔍 PD Jobs Europe — {today}", body)


if __name__ == "__main__":
    main()
